# a custom ftp-server which i can connect my network-scanner to. 
# the scanner writes the files to the ftp-server, 
# which is the same as the consume-folder paperless-ngx...

services:
    ftp-server:
        container_name: ${FTP_CONTAINER_NAME}
        environment:
            - FTP_PASS=${FTP_PASSWORD}
            - FTP_USER=${FTP_USERNAME}
        image: garethflowers/ftp-server
        ports:
            - "20-21:20-21/tcp"
            - "40000-40009:40000-40009/tcp" # For passive mode
        volumes:
            - "${PAPERLESS_CONSUME_PATH}:/home/${FTP_USERNAME}}"
        restart: always
